### ISSUE TITLE
Kindle Download - 0.3.1 only downloading one book at a time

### ISSUE THREAD

**Issue by hillcountryfare** [husjon/tampermonkey#3]
Since upgrading to 0.3.1 when I have multiple books checked only the first book downloads before there's an error.
![2023-08-23 15_54_06-Amazon com_ Manage Your Content and Devices — Mozilla Firefox](https://github.com/husjon/tampermonkey/assets/69683612/cdd7276f-c462-4ec0-a99d-ccbda7380996)
[console-export-2023-8-23_15-53-46.txt](https://github.com/husjon/tampermonkey/files/12423264/console-export-2023-8-23_15-53-46.txt)

**Comment by husjon** [comment]
This us while using Firefox?

I'm using Chrome myself and I've yet to see the issue first hand.

I can take a look at it some time tomorrow.

**Comment by hillcountryfare** [comment]
Yeah Firefox. The prior version worked wonderful!  Not in a rush and appreciate your effort.

Sent from my iPhone

On Aug 23, 2023, at 17:37, Jon Erling Hustadnes ***@***.***> wrote:

﻿

This us while using Firefox?

I'm using Chrome myself and I've yet to see the issue first hand.

I can take a look at it some time tomorrow.

**Comment by husjon** [comment]
Hi, this should now be fixed with #4 (v0.3.2).
I slowed down the download method a bit and made it do a couple of attempts to get to the notification-close button.

I will need to do some more work in the near future to make it a bit more robust, but this should work for now. :)

**Comment by husjon** [comment]
I'll be closing this issue now, but do feel free to reopen if you're experiencing the same issue.

**Comment by hillcountryfare** [comment]
I'm sorry, I'm new to this.  The changes you made resolved the issue.  I made some tweaks to the timing as the entire delay wasn't necessary.  I changed the for loop to be 0 - 3 and that still worked great!

**Comment by husjon** [comment]
No worries, glad to hear it's working.

I'll keep in mind the for loop changes when I do some more work on it. :+1:
